In [ ]:
## Importing NumPy
import numpy as np

## Create array using numpy
## Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)
print(type(array_1d))
print(array_1d.shape)

1D Array:
[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [34]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1.reshape(1,5) #1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [35]:
arr1 = np.array([[1, 2, 3, 4, 5]])
arr1.shape

(1, 5)

In [36]:
## Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)
print(type(array_2d))
print(array_2d.shape)


2D Array:
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [37]:
np.arange(0, 10, 2) #start, stop, step

array([0, 2, 4, 6, 8])

In [38]:
np.arange(0, 10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [39]:
np.ones((3, 3)) # Create a 3x3 array filled with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
## Identity matrix
np.eye(3) # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print('Array: \n', arr)
print('Shape of the array:', arr.shape)
print('Number of dimensions:', arr.ndim)
print('Data type of the array:', arr.dtype)
print('Size of the array:', arr.size)
print('Item size in bytes:', arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape of the array: (2, 3)
Number of dimensions: 2
Data type of the array: int64
Size of the array: 6
Item size in bytes: 8


In [43]:
### Numpy Vectorized Operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

### Element Wise Addition
arr_sum = arr1 + arr2
print("Element-wise addition:", arr_sum)

### Element Wise Subtraction
print("Element-wise subtraction:", arr2 - arr1)

### Element Wise Multiplication
print("Element-wise multiplication:", arr1 * arr2)

### Element Wise Division
print("Element-wise division:", arr2 / arr1)


Element-wise addition: [11 22 33 44 55]
Element-wise subtraction: [ 9 18 27 36 45]
Element-wise multiplication: [ 10  40  90 160 250]
Element-wise division: [10. 10. 10. 10. 10.]


In [49]:
### Universal Functions
arr = np.array([2, 3, 4, 5, 6])

### Square Root
sqrt_arr = np.sqrt(arr)
print("Square root of arr:", sqrt_arr)

### Exponential
exp_arr = np.exp(arr)
print("Exponential of arr:", exp_arr)

### Sine
sin_arr = np.sin(arr)
print("Sine of arr:", sin_arr)  

### Natural Logarithm
log_arr = np.log(arr)
print("Natural logarithm of arr:", log_arr)

Square root of arr: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential of arr: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine of arr: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural logarithm of arr: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [50]:
### Array Slicing and Indexing
arr = np.array([10, 20, 30, 40, 50])

### Slicing
print("First three elements:", arr[:3])
print("Last two elements:", arr[-2:])

### Indexing
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])

### Boolean Indexing
bool_index = arr > 30
print("Elements greater than 30:", arr[bool_index])

### Reshaping Arrays
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)
reshaped_arr = arr.reshape(1, 9)  # Reshape to 1 row and 9 columns
print("Reshaped array:\n", reshaped_arr)

First three elements: [10 20 30]
Last two elements: [40 50]
Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Elements greater than 30: [40 50]
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array:
 [[1 2 3 4 5 6 7 8 9]]


In [52]:
### Modifying Array Elements
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)
arr[0, 0] = 10  # Change the first element
print("Modified array:\n", arr)
arr[1:]= 100  # Change all elements in the second row to 100
print("Array after modifying second row:\n", arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified array:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
Array after modifying second row:
 [[ 10   2   3]
 [100 100 100]
 [100 100 100]]


In [53]:
### Statistical Concepts - Normalization to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

## Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

## Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)


Mean: 3.0
Standard Deviation: 1.4142135623730951
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [54]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

## Mean
mean = np.mean(data)
print("Mean:", mean)

## Median
median = np.median(data)
print("Median:", median)

## Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

## Variance
variance = np.var(data)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [55]:
## Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [56]:
data[data > 5]  # Get elements greater than 5

array([ 6,  7,  8,  9, 10])

In [57]:
data[data < 5]  # Get elements less than 5

array([1, 2, 3, 4])

In [60]:
data[(data > 5) & (data < 8)]  # Get elements greater than 5 and less than 8

array([6, 7])

In [61]:
data[(data > 5) | (data < 8)] # Get elements greater than 5 or less than 8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])